language: cpp
os: windows
compiler: clang
before_install: skip
before_script: 
  - choco install re2c
  - curl -o /C/php-devel-pack-7.4.2-Win32-vc15-x64.zip https://windows.php.net/downloads/releases/php-devel-pack-7.4.2-Win32-vc15-x64.zip
  - 7z x /C/php-devel-pack-7.4.2-Win32-vc15-x64.zip
  - cmd.exe /C/php-devel-pack-7.4.2-Win32-vc15-x64/phpize.bat
  - cmd.exe configure.bat --with-opencv
script:
  - nmake
install: skip
after_success: skip
after_script: skip

