# Generated by configure.js
PHP_SRC_DIR =G:\php\php_opencv_win
PHP_CL=cl.exe 

PHP_COMPILER_SHORT=vc15 

PHP_ARCHITECTURE=x64 

LINK=link.exe 

NMAKE=nmake.exe 

MAKE_LIB=lib.exe 

BISON=bison.exe 

SED=sed.exe 

ZIP=zip.exe 

MC=D:\cygwin64\bin\mc.exe 

MT=D:\cygwin64\bin\mt.exe 

PHP_PREFIX=C:\php 

BASE_INCLUDES=/I G:\php\php-devel-pack-7.4.2-Win32-vc15-x64/include /I G:\php\php-devel-pack-7.4.2-Win32-vc15-x64/include/main /I G:\php\php-devel-pack-7.4.2-Win32-vc15-x64/include/Zend /I G:\php\php-devel-pack-7.4.2-Win32-vc15-x64/include/TSRM /I G:\php\php-devel-pack-7.4.2-Win32-vc15-x64/include/ext 

CFLAGS_PHP_OBJ=$(CFLAGS_PHP) $(STATIC_EXT_CFLAGS) 

DLL_LDFLAGS=/dll 

PHP_LDFLAGS=$(DLL_LDFLAGS) /nodefaultlib:libcmt 

LIBS=kernel32.lib ole32.lib user32.lib advapi32.lib shell32.lib ws2_32.lib Dnsapi.lib psapi.lib bcrypt.lib imagehlp.lib 

ZTS=1 

PHP_ZTS_ARCHIVE_POSTFIX= 

BUILD_DIR=G:\php\php_opencv_win\x64\Release_TS 

PHPDLL=php7ts.dll 

PHPLIB=php7ts.lib 

PHP_BUILD=G:\php\php_opencv_win\no 

CFLAGS=/nologo $(BASE_INCLUDES) /D _WINDOWS /D WINDOWS=1 /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3 /D _USE_MATH_DEFINES /FD /wd4996 /Qspectre /guard:cf /Zc:inline /Zc:__cplusplus /d2FuncCache1 /Zc:wchar_t /MP /LD /MD /W3 /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /D ZTS=1 /I "G:\php\php_opencv_win\no\include" 

LDFLAGS=/nologo /GUARD:CF /libpath:"\"G:\php\php_opencv_win\no\lib\"" 

ARFLAGS=/libpath:"\"G:\php\php_opencv_win\no\lib\"" 

SNAPSHOT_TEMPLATE=no 

PHP_DIR=G:\php\php-devel-pack-7.4.2-Win32-vc15-x64 

PHP_SIMD_SCALE=SSE2 

LDFLAGS_OPENCV=/libpath:"libx64" 

ARFLAGS_OPENCV=/libpath:"libx64" 

LIBS_OPENCV=opencv_world420.lib 

CFLAGS_PHP=/D _USRDLL /D PHP7DLLTS_EXPORTS /D PHP_EXPORTS /D LIBZEND_EXPORTS /D TSRM_EXPORTS /D SAPI_EXPORTS /D WINVER=0x0601 /D COMPILE_DL_OPENCV 

CFLAGS_BD_=/Fp$(BUILD_DIR)\\ /FR$(BUILD_DIR)\\ /Fd$(BUILD_DIR)\\ 

CFLAGS_BD_SOURCE_OPENCV2_CORE_HAL=/Fp$(BUILD_DIR)\source\opencv2\core\hal\ /FR$(BUILD_DIR)\source\opencv2\core\hal\ /Fd$(BUILD_DIR)\source\opencv2\core\hal\ 

CFLAGS_BD_SOURCE_OPENCV2_CORE=/Fp$(BUILD_DIR)\source\opencv2\core\ /FR$(BUILD_DIR)\source\opencv2\core\ /Fd$(BUILD_DIR)\source\opencv2\core\ 

CFLAGS_BD_SOURCE_OPENCV2_FACE=/Fp$(BUILD_DIR)\source\opencv2\face\ /FR$(BUILD_DIR)\source\opencv2\face\ /Fd$(BUILD_DIR)\source\opencv2\face\ 

CFLAGS_BD_SOURCE_OPENCV2=/Fp$(BUILD_DIR)\source\opencv2\ /FR$(BUILD_DIR)\source\opencv2\ /Fd$(BUILD_DIR)\source\opencv2\ 

OPENCV_GLOBAL_OBJS=$(BUILD_DIR)\\opencv.obj $(BUILD_DIR)\\opencv_exception.obj $(BUILD_DIR)\source\opencv2\core\hal\opencv_interface.obj $(BUILD_DIR)\source\opencv2\core\opencv_base.obj $(BUILD_DIR)\source\opencv2\core\opencv_cvdef.obj $(BUILD_DIR)\source\opencv2\core\opencv_mat.obj $(BUILD_DIR)\source\opencv2\core\opencv_persistence.obj $(BUILD_DIR)\source\opencv2\core\opencv_type.obj $(BUILD_DIR)\source\opencv2\core\opencv_utility.obj $(BUILD_DIR)\source\opencv2\face\opencv_facerec.obj $(BUILD_DIR)\source\opencv2\opencv_core.obj $(BUILD_DIR)\source\opencv2\opencv_face.obj $(BUILD_DIR)\source\opencv2\opencv_highgui.obj $(BUILD_DIR)\source\opencv2\opencv_imgcodecs.obj $(BUILD_DIR)\source\opencv2\opencv_imgproc.obj $(BUILD_DIR)\source\opencv2\opencv_ml.obj $(BUILD_DIR)\source\opencv2\opencv_objdetect.obj $(BUILD_DIR)\source\opencv2\opencv_videoio.obj 

OPENCV_GLOBAL_OBJS_RESP=@"G:\php\php_opencv_win\x64\Release_TS\resp\OPENCV_GLOBAL_OBJS.txt" 

EXT_TARGETS=php_opencv.dll 

CFLAGS_OPENCV_OBJ=$(CFLAGS_OPENCV) 

CFLAGS_OPENCV=/EHcs /D _ALLOW_KEYWORD_MACROS /D __STDC_LIMIT_MACROS /I "include" /DHAVE_OPENCV2_OPENCV_HPP=1 /FI main/config.pickle.h /D COMPILE_DL_OPENCV /D OPENCV_EXPORTS=1 /D ZEND_WIN32_KEEP_INLINE=1 /U ZEND_WIN32_FORCE_INLINE 

BUILD_DIRS_SUB=G:\php\php_opencv_win\x64\Release_TS source source\opencv2 source\opencv2\core source\opencv2\core\hal source\opencv2\face 


CC="$(PHP_CL)"
LD="$(LINK)"
MC="$(MC)"
MT="$(MT)"

PHPSDK_DIR=$(PHP_DIR)
PHPLIB=$(PHPSDK_DIR)\lib\$(PHPLIB)
LDFLAGS=$(LDFLAGS) /libpath:"$(PHPSDK_DIR)\lib\;$(PHPSDK_DIR)"
BUILD_DIR_DEV=$(PHPSDK_DIR)

!if "$(DEBUGGER)" == "1"
DEBUGGER_CMD=devenv
DEBUGGER_ARGS=/debugexe
!else
DEBUGGER_CMD=
DEBUGGER_ARGS=
!endif

all: $(EXT_TARGETS) $(PECL_TARGETS)

build_dirs: $(BUILD_DIR) $(BUILD_DIRS_SUB)

clean-pecl:
	@echo Cleaning PECL targets only
	-rd /s /q $(BUILD_DIR)\pecl

clean-all:
	@echo Cleaning standard build dirs
	cd $(BUILD_DIR)
	@for %D in (_x $(BUILD_DIRS_SUB)) do @if exist %D @rd /s /q %D
	-@del /f /q $(BUILD_DIR)\*.res $(BUILD_DIR)\*.manifest $(BUILD_DIR)\*.lib $(BUILD_DIR)\*.ilk $(BUILD_DIR)\*.pdb $(BUILD_DIR)\*.exp $(PHPDEF) $(BUILD_DIR)\*.rc $(BUILD_DIR)\*.dbg $(BUILD_DIR)\*.bin $(BUILD_DIR)\php*.dll $(BUILD_DIR)\php*.exe > NUL

clean: clean-pecl
	@echo Cleaning distribution build dirs
	cd $(BUILD_DIR)
	@for %D in (_x $(BUILD_DIRS_SUB)) do @if exist %D @del /F /Q %D\*.* > NUL
	-@del /F /Q $(BUILD_DIR)\*.res $(BUILD_DIR)\*.lib $(BUILD_DIR)\*.ilk $(BUILD_DIR)\*.pdb $(BUILD_DIR)\*.exp $(PHPDEF) $(BUILD_DIR)\php-$(PHP_VERSION_STRING)-Win32.zip $(BUILD_DIR)\pecl-$(PHP_VERSION_STRING)-Win32.zip > NUL

!if "$(EXT_TARGETS)" == ""
_EXTENSION_DLL=$(PECL_TARGETS)
!else
_EXTENSION_DLL=$(EXT_TARGETS)
!endif

test: set-tmp-env
	$(DEBUGGER_CMD) $(DEBUGGER_ARGS) "$(PHP_PREFIX)\php.exe" -d open_basedir= -d output_buffering=0 run-tests.php $(TESTS) -p "$(PHP_PREFIX)\php.exe" -d extension=$(BUILD_DIR)\$(_EXTENSION_DLL)

run: set-tmp-env
	$(DEBUGGER_CMD) $(DEBUGGER_ARGS) "$(PHP_PREFIX)\php.exe" -n -d extension=$(BUILD_DIR)\\$(_EXTENSION_DLL) $(ARGS)

!if $(MT) == ""
_VC_MANIFEST_EMBED_EXE=
_VC_MANIFEST_EMBED_DLL=
!else
_VC_MANIFEST_EMBED_EXE= if exist $@.manifest $(MT) -nologo -manifest $@.manifest -outputresource:$@;1
_VC_MANIFEST_EMBED_DLL= if exist $@.manifest $(MT) -nologo -manifest $@.manifest -outputresource:$@;2
!endif

install: build-headers  build-bins
build-headers:
	@if not exist $(BUILD_DIR_DEV)\include mkdir $(BUILD_DIR_DEV)\include >nul
	@for %D in ($(INSTALL_HEADERS_DIR)) do @if not exist $(BUILD_DIR_DEV)\include\%D mkdir $(BUILD_DIR_DEV)\include\%D >nul
	@for %D in ($(INSTALL_HEADERS_DIR)) do @copy %D*.h $(BUILD_DIR_DEV)\include\%D /y >nul

build-bins:
	@copy $(BUILD_DIR)\php_opencv.lib $(BUILD_DIR_DEV)\lib
  @if not exist $(PHP_PREFIX) mkdir $(PHP_PREFIX) >nul
  @if not exist $(PHP_PREFIX)\ext mkdir $(PHP_PREFIX)\ext >nul
	@copy $(BUILD_DIR)\php_opencv.dll $(PHP_PREFIX)\ext

set-tmp-env:
	@set PATH=$(PHP_BUILD)\bin;$(PATH)


dump-tmp-env: set-tmp-env
	@set



# objects for EXT opencv

$(BUILD_DIR)\\opencv.obj $(BUILD_DIR)\\opencv_exception.obj $(BUILD_DIR)\source\opencv2\core\hal\opencv_interface.obj $(BUILD_DIR)\source\opencv2\core\opencv_base.obj $(BUILD_DIR)\source\opencv2\core\opencv_cvdef.obj $(BUILD_DIR)\source\opencv2\core\opencv_mat.obj $(BUILD_DIR)\source\opencv2\core\opencv_persistence.obj $(BUILD_DIR)\source\opencv2\core\opencv_type.obj $(BUILD_DIR)\source\opencv2\core\opencv_utility.obj $(BUILD_DIR)\source\opencv2\face\opencv_facerec.obj $(BUILD_DIR)\source\opencv2\opencv_core.obj $(BUILD_DIR)\source\opencv2\opencv_face.obj $(BUILD_DIR)\source\opencv2\opencv_highgui.obj $(BUILD_DIR)\source\opencv2\opencv_imgcodecs.obj $(BUILD_DIR)\source\opencv2\opencv_imgproc.obj $(BUILD_DIR)\source\opencv2\opencv_ml.obj $(BUILD_DIR)\source\opencv2\opencv_objdetect.obj $(BUILD_DIR)\source\opencv2\opencv_videoio.obj: G:\php\php_opencv_win\opencv.cc G:\php\php_opencv_win\opencv_exception.cc G:\php\php_opencv_win\source\opencv2\core\hal\opencv_interface.cc G:\php\php_opencv_win\source\opencv2\core\opencv_base.cc G:\php\php_opencv_win\source\opencv2\core\opencv_cvdef.cc G:\php\php_opencv_win\source\opencv2\core\opencv_mat.cc G:\php\php_opencv_win\source\opencv2\core\opencv_persistence.cc G:\php\php_opencv_win\source\opencv2\core\opencv_type.cc G:\php\php_opencv_win\source\opencv2\core\opencv_utility.cc G:\php\php_opencv_win\source\opencv2\face\opencv_facerec.cc G:\php\php_opencv_win\source\opencv2\opencv_core.cc G:\php\php_opencv_win\source\opencv2\opencv_face.cc G:\php\php_opencv_win\source\opencv2\opencv_highgui.cc G:\php\php_opencv_win\source\opencv2\opencv_imgcodecs.cc G:\php\php_opencv_win\source\opencv2\opencv_imgproc.cc G:\php\php_opencv_win\source\opencv2\opencv_ml.cc G:\php\php_opencv_win\source\opencv2\opencv_objdetect.cc G:\php\php_opencv_win\source\opencv2\opencv_videoio.cc
	$(CC) $(CFLAGS_OPENCV_OBJ) $(CFLAGS) /Fo$(BUILD_DIR)\\ $(CFLAGS_BD_) /c G:\php\php_opencv_win\opencv.cc G:\php\php_opencv_win\opencv_exception.cc 
	$(CC) $(CFLAGS_OPENCV_OBJ) $(CFLAGS) /Fo$(BUILD_DIR)\source\opencv2\core\hal\ $(CFLAGS_BD_SOURCE_OPENCV2_CORE_HAL) /c G:\php\php_opencv_win\source\opencv2\core\hal\opencv_interface.cc 
	$(CC) $(CFLAGS_OPENCV_OBJ) $(CFLAGS) /Fo$(BUILD_DIR)\source\opencv2\core\ $(CFLAGS_BD_SOURCE_OPENCV2_CORE) /c G:\php\php_opencv_win\source\opencv2\core\opencv_base.cc G:\php\php_opencv_win\source\opencv2\core\opencv_cvdef.cc G:\php\php_opencv_win\source\opencv2\core\opencv_mat.cc G:\php\php_opencv_win\source\opencv2\core\opencv_persistence.cc G:\php\php_opencv_win\source\opencv2\core\opencv_type.cc G:\php\php_opencv_win\source\opencv2\core\opencv_utility.cc 
	$(CC) $(CFLAGS_OPENCV_OBJ) $(CFLAGS) /Fo$(BUILD_DIR)\source\opencv2\face\ $(CFLAGS_BD_SOURCE_OPENCV2_FACE) /c G:\php\php_opencv_win\source\opencv2\face\opencv_facerec.cc 
	$(CC) $(CFLAGS_OPENCV_OBJ) $(CFLAGS) /Fo$(BUILD_DIR)\source\opencv2\ $(CFLAGS_BD_SOURCE_OPENCV2) /c G:\php\php_opencv_win\source\opencv2\opencv_core.cc G:\php\php_opencv_win\source\opencv2\opencv_face.cc G:\php\php_opencv_win\source\opencv2\opencv_highgui.cc G:\php\php_opencv_win\source\opencv2\opencv_imgcodecs.cc G:\php\php_opencv_win\source\opencv2\opencv_imgproc.cc G:\php\php_opencv_win\source\opencv2\opencv_ml.cc G:\php\php_opencv_win\source\opencv2\opencv_objdetect.cc G:\php\php_opencv_win\source\opencv2\opencv_videoio.cc 

$(BUILD_DIR)\php_opencv.dll.res: $(PHP_DIR)\build\template.rc
	$(RC) /nologo  $(BASE_INCLUDES) /I $(PHP_DIR)/include /n /fo $(BUILD_DIR)\php_opencv.dll.res /d FILE_DESCRIPTION="\"opencv\"" /d FILE_NAME="\"php_opencv.dll\"" /d URL="\"http://www.php.net\"" /d INTERNAL_NAME="\"OPENCV extension\"" /d THANKS_GUYS="\"\"" $(PHP_DIR)\build\template.rc

$(BUILD_DIR)\php_opencv.dll.manifest: G:\php\php-devel-pack-7.4.2-Win32-vc15-x64\build\default.manifest
	@copy G:\php\php-devel-pack-7.4.2-Win32-vc15-x64\build\default.manifest $(BUILD_DIR)\php_opencv.dll.manifest >nul
$(BUILD_DIR)\php_opencv.lib: $(BUILD_DIR)\php_opencv.dll

$(BUILD_DIR)\php_opencv.dll: $(DEPS_OPENCV) $(OPENCV_GLOBAL_OBJS) $(PHPLIB) $(BUILD_DIR)\php_opencv.dll.res $(BUILD_DIR)\php_opencv.dll.manifest
	"$(LINK)" $(OPENCV_GLOBAL_OBJS_RESP) $(PHPLIB) $(LIBS_OPENCV) $(LIBS) $(BUILD_DIR)\php_opencv.dll.res /out:$(BUILD_DIR)\php_opencv.dll $(DLL_LDFLAGS) $(LDFLAGS) $(LDFLAGS_OPENCV)
	-@$(_VC_MANIFEST_EMBED_DLL)

php_opencv.dll: $(BUILD_DIR)\php_opencv.dll
	@echo EXT opencv build complete



